/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.github.lingocoder;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class WtfShouldIDo {
    @Test void wtLiteralFShouldItDo() {
        Wtf classUnderTest = new Wtf();
        assertTrue(classUnderTest.wtLiteralF(), "wtLiteralF should return 'true'");
    }
}
